src/faq/urls.py
from django.urls import path

from faq.views import faq_index

urlpatterns = [
    path("",faq_index, name="faq")
]

src/root/urls.py
from django.contrib import admin
from django.urls import path,include

from .settings import BASE_DIR
from .views import base_index


urlpatterns = [
    path('admin/', admin.site.urls), # Attention le "admin" utiliser dans plusieurs url
    path('', base_index,name='index'),
    path('service/', include('service.urls')),
    path('contact/', include('contact.urls')),
    path('actualite/', include('actualite.urls')),

    path('presentation/', include('presentation.urls')),
    path('coin-du-consultant/', include('coin_consultant.urls')),
    path('faq/', include('faq.urls')),
    path('formation/', include('formation.urls')),
    path('emploi/', include('emploi.urls')),
    path('compte/', include('compte.urls')),
    path('recruteur/', include('coin_du_recurteur.urls')),
    path('admin-p/', include('admin_personnaliser.urls')),

]

src/equipe/models.py
from django.db import models

# Create your models here.

RESEUX_LISTE = [
    ("twitter","Twitter"),
    ("facebook","Facebook"),
    ("instagram","Instagram"),
    ("linkedIn","LinkedIn")
]

class Poste(models.Model):
    nom = models.CharField(max_length=300,unique=True,verbose_name="Nom du poste")

    def __str__(self):
        return self.nom


class Membre(models.Model):
    nom = models.CharField(max_length=300)
    prenom = models.CharField(max_length=300, verbose_name="Prénom")
    poste = models.ForeignKey(Poste,on_delete=models.SET_NULL,null=True, verbose_name="Le poste")
    numero = models.CharField(max_length=20, verbose_name='Numéro de téléphone') # utilise une librairie externe à django
    image = models.ImageField(upload_to="equipe/%Y/%m/%d", verbose_name="Image 500x500")

    def __str__(self):
        return f"{self.nom} {self.prenom}"

class ReseauSocial(models.Model):
    nom_reseau = models.CharField(max_length=40,choices=RESEUX_LISTE)
    url = models.URLField(max_length=300, unique=True)
    proprietaire = models.ForeignKey(Membre,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nom_reseau} - {self.proprietaire.nom}"

src/root/views.py
from django.shortcuts import render

from actualite.models import Actualite
from equipe.models import Membre
from faq.models import FaqModel
from outils.mailer import send
from presentation.models import AProposModel
from service.models import *
from slider.models import *


def base_index(request):
    apropos_video = AProposModel.objects.all()
    all_faq = FaqModel.objects.all()
    services = Service.objects.all()
    actualite = Actualite.objects.all()
    sliders = Slider.objects.all()
    #recup équipe
    membres = Membre.objects.all()
    context = {'services': services, "apropos_video": apropos_video, "all_faq": all_faq,"actualite":actualite,"membres":membres,"sliders":sliders}
    return render(request, "index.html", context)

# pour les video et l'image

src/root/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>
    {% block title %}
        
    {% endblock title %}
  </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png'%}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/main.css'%}" rel="stylesheet">
  <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

  <!-- =======================================================
  * Template Name: Impact
  * Updated: Jul 27 2023 with Bootstrap v5.3.1
  * Template URL: https://bootstrapmade.com/impact-bootstrap-business-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <!-- Alertify CSS -->
        <link rel="stylesheet"
            href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
        <!-- Alertify Default theme -->
        <link rel="stylesheet"
            href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css" />



</head>

<body>

  <!-- ======= Header ======= -->
  <section id="topbar" class="topbar d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:kamba.dembele@cafemali.com">kamba.dembele@cafemali.com</a></i>
        <i class="bi bi-phone d-flex align-items-center ms-4"><span> +223 20 71 22 22 / 66 95 49 94</span></i>
      </div>
      <div class="social-links d-none d-md-flex align-items-center">
        <a href="https://www.facebook.com/Cafesarl/" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="https://www.facebook.com/Cafesarl/" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="https://www.linkedin.com/company/cafe-sarl/" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </section>
  <!-- End Top Bar -->

  <header id="header" class="header d-flex align-items-center">

    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
      <a href="{% url 'index' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>CAFE SARL<span> </span></h1>
      </a>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'index' %}">Acceuil</a></li>
          <li><a href="{% url 'presentation'  %}">Présentation</a></li>

          <li><a href="{% url 'actualite_index' %}">Actualités</a></li>



            <li class="dropdown"><a href="#"><span>Service</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                <ul>
                  <li><a href="{% url 'formation_index' %}">Formations</a></li>

                  <li><a href="{% url 'service_index' %}">Services</a></li>
                </ul>
              </li>


            <li class="dropdown"><a href="#"><span>Autre</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                <ul>
                  <li><a href="{% url 'emploi_index' %}">Offre d'emplois</a></li>
                  <li><a href="{% url 'coin_consultant'  %}">Coin du Consultant</a></li>
                  <li><a href="{% url 'contact_index' %}">Contact</a></li>
                </ul>
              </li>

          {% if not user.is_authenticated%}
            <li><a href="{% url 'my_login' %}">Connexion</a></li>
          {% endif %}

          {% if user.is_authenticated%}
            <li><a href="{% url 'contact_index' %}"></a></li>
            <div class="dropdown">
                <li class="dropdown"><a href="#"><span>Compte</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                <ul>

                  {% if user.type_compte == "candidat" %}
                    <li><a href="{% url 'profile_candidat' %}">Profil</a></li>
                  {% endif %}

                  {% if user.type_compte == "recruteur"%}
                    <li><a href="{% url 'profile_recruteur' %}">Profil</a></li>
                  {% endif %}

                  {% if user.type_compte == "admin"%}
                    <li><a href="{% url 'profile_admin' %}">Profil</a></li>
                  {% endif %}



                  <li><a href="{% url 'my_logout'%}">Déconnexion</a></li>
                </ul>
              </li>
            </div>
          {% endif %}



        </ul>
      </nav><!-- .navbar -->

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header><!-- End Header -->
  <!-- End Header -->
  <main id="main">
     {% block body %}
    
    {% endblock body %}
  </main>
  <!-- End Hero Section -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
          <a href="" class="logo d-flex align-items-center">
            <span>CAFE SARL</span>
          </a>
          <p>CAFE SARL est un cabinet de conseil et d’assistance en gestion fiscale et    sociale spécialisé dans la formation et gestion des compétences. Nous sommes une équipe vouée à la tache avec des compétences diverses ayant pour souci d’offrir une meilleure qualité de travail à ceux qui nous font confiance.</p>
          <div class="social-links d-flex mt-4">
              <a href="https://www.facebook.com/Cafesarl/" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="https://www.facebook.com/Cafesarl/" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="https://www.linkedin.com/company/cafe-sarl/" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Liens utiles</h4>
          <ul>
            <li><a href="#">Presentation</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Actualites</a></li>
             <li><a href="{% url 'coin_consultant'  %}">Coin du Consultant</a></li>
          <li><a href="{% url 'contact_index' %}">Contact</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>FAQ</h4>
          <ul>
            <li><a href="{% url 'faq' %}">FAQ</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contactez-nous</h4>
          <p>
            Kalabanco pres du Marche <br>
            Immeuble SOMOYAF Station No 2<br>
            Bamako Mali <br><br>
            <strong>Tel:</strong> +223 20 71 22 22 / 66 95 49 94<br>
            <strong>Email:</strong> <a href="mailto:kamba.dembele@cafemali.com" class="text-white" target="_blank">kamba.dembele@cafemali.com</a><br>
          </p>

        </div>

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
        &copy; Copyright <strong><span>CAFE SARL</span></strong>. Tous les droits sont réservés
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/impact-bootstrap-business-website-template/ -->
<!--        Designed by <a href="">@</a>-->
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <!-- Alertify JavaScript cdn link -->
        <script
            src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
            <script>
            alertify.set('notifier','position', 'top-right')

            {% for msg in messages %}
              alertify.success('{{ msg }}')
            {% endfor %}
            
        </script>

</body>

</html>

  {% block custom_syles %}
  {% endblock custom_syles %}

src/root/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Acceuil - CAFE SARL {% endblock title %}
{% block body %}

<!-- ======= Hero Section ======= -->
<!-- <section id="hero" class="hero">
    <div class="container position-relative">
      <div class="row gy-5" data-aos="fade-in">
        <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center text-center text-lg-start">
          <h2>Bienvenue Chez <span>CAFE SARL</span></h2>
          <p class="text-white">cabinet de conseil et d’assistance en gestion fiscale spécialisé dans la formation et gestion des....</p>
          <div class="d-flex justify-content-center justify-content-lg-start">
            <a href="{% url 'presentation'  %}" class="btn-get-started">En savoir plus</a>
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2">
          <img src="{% static 'assets/img/56149800.jpg' %}" class="img-fluid" alt="" data-aos="zoom-out" data-aos-delay="100">
        </div>
      </div>
    </div>
    </div>
  </section> -->
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    {% for item in sliders %}
    <div style="background: #000;"  class="carousel-item {% if forloop.first %}active{% endif %}">
      <img style="opacity: .5;" src="{% static item.image %}" class="d-block w-100" alt="...">

      <div
        class="carousel-caption d-flex justify-content-center align-items-center">
        <div class="text-center">
          <h5>{{ item.titre }}</h5>
          <p>{{ item.reference }}.</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button"
    data-bs-target="#carouselExampleCaptions"
    data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button"
    data-bs-target="#carouselExampleCaptions"
    data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<!-- End Hero Section -->

<section class="portfolio  bg-white">
  <div class="container" data-aos="fade-up">

    <div class="container text-center text-black">

      <p class>

        <b class="text-bleu">CAFE SARL</b>
        est un cabinet de conseil et d’assistance en gestion fiscale et sociale
        spécialisé dans
        <b class="text-bleu">la formation et gestion des compétences. </b>
        Nous sommes une équipe vouée à la tache avec des compétences diverses
        ayant pour souci d’offrir une meilleure qualité de travail à ceux qui
        nous font confiance.

      </p>
    </div>
  </div>

</section>

<!-- ======= Our Services Section ======= -->
<section id="services" class="services sections-bg">
  <div class="container" data-aos="fade-up">

    <div class="section-header">
      <h2 class="text-bleu">Les Services</h2>
      <p>Nous offrons des services de qualité en matière de</p>
    </div>

    <div class="row gy-4" data-aos="fade-up" data-aos-delay="100">

      {% for item in services %}
      <div class="col-lg-4 col-md-6">
        <div class="service-item  position-relative">
          <div class="text-center mb-3">
            <img src="{% static item.image %}" width="96" height="96">
          </div>
          <h3>{{ item.titre }}</h3>
          <p>{{ item.description }}.</p>
          <a href="{% url 'servicedetail' item.titre %}"
            class="readmore stretched-link">Detail <i
              class="bi bi-arrow-right"></i></a>
        </div>
      </div>
      {% endfor %}

    </div>

  </div>
</section><!-- End Our Services Section -->

<section class="portfolio " style="background:#1e1e1e;">
  <div class="container" data-aos="fade-up">

    <div class="container text-center text-white">

      <p class="h2 mt-0">Besoin d'une proposition</p>
      <p class="h6 mb-2">Contactez-nous et nous vous répondrons avec toutes les
        informations dans les plus brefs délais.</p>
      <p class="mt-4"><a href="{% url 'contact_index' %}"
          class="btn btn-primary">Contactez-nous</a></p>
    </div>
  </div>

</section>

<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio sections-bg">
  <div class="container" data-aos="fade-up">

    <div class="section-header">
      <h2 class="text-bleu">Actualites</h2>
      <!-- <p>Quam sed id excepturi ccusantium dolorem ut quis dolores nisi
                llum nostrum enim velit qui ut et autem uia reprehenderit sunt
                deleniti</p> -->
    </div>

    <div class="portfolio-isotope" data-portfolio-filter="*"
      data-portfolio-layout="masonry" data-portfolio-sort="original-order"
      data-aos="fade-up" data-aos-delay="100">
      <div class="row gy-4 portfolio-container">
        {% for item in actualite %}
        <div class="col-xl-4 col-md-6 portfolio-item filter-app">
          <div class="portfolio-wrap">
            <a href="{% static item.image %}"
              data-gallery="portfolio-gallery-app"
              class="glightbox"><img
                src="{% static item.image %}"
                class="img-fluid" alt></a>
            <div class="portfolio-info">
              <h4><a href="{% url 'detailActualite' item.titre %}"
                  title="More Details">{{ item.titre }}</a></h4>
            </div>
          </div>
        </div>
        {% endfor %}
      </div><!-- End Portfolio Container -->

    </div>

  </div>
</section><!-- End Portfolio Section -->

<!-- ======= About Us Section ======= -->
<section id="about" class="about">
  <div class="container" data-aos="fade-up">

    <div class="section-header">
      <h2 class="text-bleu">A propos</h2>
      <!--          <p>Aperiam dolorum et et wuia molestias qui eveniet numquam nihil porro incidunt dolores placeat sunt id nobis omnis tiledo stran delop</p>-->
    </div>

    <div class="row gy-4">
      {% for apv in apropos_video %}

      {% if apv.lienVideoYoutube == None %}

      <div class="col-lg-6">

        <img src="{% static apv.image %}" class="img-fluid rounded-4 mb-4"
          alt="Image nom trouvée">
        {{apv.description | safe}}
      </div>

      {% else %}

      <div class="col-lg-6">
        <div class="content ps-0 ps-lg-5">
          <p class="fst-italic">
            {{apv.description | safe}}
          </p>
          <!--              <ul>-->
          <!--                <li><i class="bi bi-check-circle-fill"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>-->
          <!--                <li><i class="bi bi-check-circle-fill"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>-->
          <!--                <li><i class="bi bi-check-circle-fill"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>-->
          <!--              </ul>-->
          <p>
            <!--                Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate-->
            <!--                velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident-->
          </p>

          <div class="position-relative mt-4">

            <img src="{% static apv.image %}" class="img-fluid rounded-4" alt>
            <a href="{{ apv.lienVideoYoutube}}" class="glightbox play-btn"></a>

          </div>
        </div>
      </div>
      {% endif %}

      {% empty %}
      <div class="container text-center h3">
        Rien à afficher pour le monent
      </div>
      {% endfor %}
      <!--          <div class="col-lg-6">-->
      <!--            <h3>Voluptatem dignissimos provident quasi corporis</h3>-->
      <!--            <img src="assets/img/about.jpg" class="img-fluid rounded-4 mb-4" alt="">-->
      <!--            <p>Ut fugiat ut sunt quia veniam. Voluptate perferendis perspiciatis quod nisi et. Placeat debitis quia recusandae odit et consequatur voluptatem. Dignissimos pariatur consectetur fugiat voluptas ea.</p>-->
      <!--            <p>Temporibus nihil enim deserunt sed ea. Provident sit expedita aut cupiditate nihil vitae quo officia vel. Blanditiis eligendi possimus et in cum. Quidem eos ut sint rem veniam qui. Ut ut repellendus nobis tempore doloribus debitis explicabo similique sit. Accusantium sed ut omnis beatae neque deleniti repellendus.</p>-->
      <!--          </div>-->

    </div>

  </div>
</section><!-- End About Us Section -->

<!-- ======= Our Team Section ======= -->
<section id="team" class="team">
  <div class="container" data-aos="fade-up">

    <div class="section-header">
      <h2>Notre équipe</h2>
      <!--          <p>Nulla dolorum nulla nesciunt rerum facere sed ut inventore quam porro nihil id ratione ea sunt quis dolorem dolore earum</p>-->
    </div>

    <div class="row gy-4">

      {% for membre in membres %}

      <div class="col-xl-3 col-md-6 d-flex" data-aos="fade-up"
        data-aos-delay="300">
        <div class="member">
          <img src="{% static membre.image.url %}" class="img-fluid" alt="Image">
          <h4>{{membre.nom}} {{membre.prenom}}</h4>
          <span>{{membre.poste.nom}}</span>
          <div class="social">
            <a href="tel:{{membre.numero}}"><i
                class="bi bi-telephone-inbound-fill"></i></a>
            {% for reseau in membre.reseausocial_set.all %}
            <a href="{{reseau.url}}"><i class="bi bi-{{reseau.nom_reseau}}"></i></a>
            {% endfor %}

            <!--                    <a href=""><i class="bi bi-facebook"></i></a>-->
            <!--                    <a href=""><i class="bi bi-instagram"></i></a>-->
            <!--                    <a href=""><i class="bi bi-linkedin"></i></a>-->
          </div>
        </div>
      </div>

      {% empty %}
      <div class="container text-center h3">Pas de membres pour le moment</div>
      {% endfor %}

    </div>

  </div>
</section><!-- End Our Team Section -->

<style>
    .text-bleu{
        color : #303090
    }
</style>

{% endblock %}